### ISSUE TITLE
Create a debian package

### ISSUE THREAD

**Issue by thomastrapp** [thomastrapp/hext#2]
Users need a way to install hext without the hassle of compiling from source.

As per debian packaging rules the project needs to be split up into at least two packages:
* libhext
* htmlext

Language bindings also need a package of their own, e.g. libhextpy.

Ideally, the packages will be accepted into the Debian repository and then automatically be mirrored by Debian derivatives, such as Ubuntu.

**Edit:** See https://github.com/thomastrapp/hext/releases/tag/v0.7.0 for the newly created (binary) Debian packages.

**Comment by impredicative** [comment]
The package v0.7.0 installed fine on Ubuntu 18.04. Thanks.
