### ISSUE TITLE
Create a MacOS package

### ISSUE THREAD

**Issue by freedmand** [thomastrapp/hext#5]
I am interested in using Hext, but there is no distribution for Mac OS X. As such, I can't install it using Pip.

**Comment by thomastrapp** [comment]
Thank you for your interest in Hext.
I unfortunately have no experience building for Mac OS X, nor do I have access to it at the moment.
Nonetheless, I'll try to see what I can do in the next couple of weeks. It would be nice for Hext to be available on all popular systems.

**Comment by freedmand** [comment]
Thanks! If you need anyone to test building it on Mac, I'm happy to help run a set of commands and see what comes out.

**Comment by thomastrapp** [comment]
Status Update: I've looked into cross-compiling for Macs, specifically [https://github.com/tpoechtrager/osxcross](https://github.com/tpoechtrager/osxcross) which looks very promising. But I felt very uneasy having no means to test the resulting binaries.
So I bought a 10 year old Macbook Pro off of Ebay :-)
I should be able to release the Hext python module for OS X in the very near future.

**Comment by thomastrapp** [comment]
Hext is now installable through pip on Mac OS X ≥ 10.11 (x86_64):
```
pip install hext
```
This will also install the htmlext command-line utility.

Requires either Python 2.7, 3.4, 3.5, 3.6 or 3.7.
The default Python version that is shipped with Mac OS X should work as well.

https://pypi.org/project/hext/#files

An easy way to test a pip install is to run the following:

```
pip install hext
git clone https://github.com/thomastrapp/hext.git
HTMLEXT="python hext/libhext/bindings/python/htmlext.py" \
  ./hext/test/blackbox.sh \
  hext/test/case/*hext
```

I have loosely documented the process of packaging Hext for Mac OS X for future reference:
https://thomastrapp.com/blog/porting-a-linux-based-binary-pypi-package-to-mac-os-x/
