### ISSUE TITLE
Node bindings and npm 

### ISSUE THREAD

**Issue by samatt** [thomastrapp/hext#6]
Hi,

First of thank you for this incredibly useful project. I was trying to use your node bindings and ran into some trouble. It seems that the NaN node module isn't supported in node v10 (which is what I need for a project). The issue I kept running into was similar to [this](https://github.com/nodejs/nan/issues/770). It totally worked on node v8.  

I was just wondering if getting it to work in node v10 was something you were interested in/had time to work on. For now I will just install it as a CLI and spawn a process in node. Additionally, any plans to put this up on an NPM registry? I like cheerio but the ability to have html templates that i can use across languages is incredibly useful.

Thanks again,

Surya

**Comment by thomastrapp** [comment]
I will definitely try to fix the build for Node v10/v11 in the coming days.

> any plans to put this up on an NPM registry?

Yes. It would be great if Hext was easily installable through npm, just like with pip.
I will look into it in the next couple of weeks.

Thank you for the kind words!

**Comment by thomastrapp** [comment]
The Hext language bindings for Node are now compatible with nodejs v8, v10 and v11:
```
cd hext/libhext/bindings/nodejs
npm install
npm run build
# run tests
./test/blackbox.js.sh ../../../../test/case/*hext
```
@samatt Thank you for the bug report - Please let me know if there are more problems.

I will leave this issue open for the npm package.

**Comment by samatt** [comment]
omg that totally worked! thanks for you insanely fast response!

**Comment by thomastrapp** [comment]
Hext for Node is now installable through npm:
```
npm install hext
```
(Does not include the htmlext command-line utility).

__Compatibility__

* Node v8, v10, v11
* Linux (GLIBC ≥2.14, basically any distribution built after the year 2012)
* Mac OS X (10.11 El Capitan or later)
* x86_64 only

https://www.npmjs.com/package/hext

Note: The Hext npm package starts at version 10. Earlier versions refer to a deprecated package of a previous owner. Npm's support is awesome and moved the package to my account.

__Testing__

An easy way to test an npm install is to run the following:
```
mkdir /tmp/hext-test
cd /tmp/hext-test
npm install hext
node -e 'require("hext")' && echo "hext loaded successfully"
git clone https://github.com/thomastrapp/hext.git
cd hext/test
cp ../libhext/bindings/nodejs/htmlext.js .
HTMLEXT="node htmlext.js" ./blackbox.sh case/*hext
```

@samatt I am closing this issue, but feel free to comment or open a new issue.

**Comment by samatt** [comment]
just writing to confirm npm install hext works! thanks again!
