### ISSUE TITLE
"All siblings of type" issue

### ISSUE THREAD

**Issue by brandonrobertz** [thomastrapp/hext#7]
I've been playing with a bunch of extractors and I encountered an issue that has confused me a bit. I'm playing with this DOM:

```
<li class="item event" >
  <div class="col-12 col-sm-2 event-type" >
    <h5 >
      Special Event
    </h5>
  </div>
    <div class="col-12 col-sm-7 item-content event-content" >
      <h3 class="title item-title event-title" >
        <a href="/events-and-training/event/3433/4377/" >Conference registration (Wednesday)</a>
      </h3>
        <p >Wednesday is a registration day.</p>
        <p >No talks scheduled.</p>
        <p ></p>
    </div>
  <div class="col-12 col-sm-3 item-meta event-meta" >
    <h4 class="event-location" >
      Salon EF
    </h4>
      <p  class="">
      3:00 pm - 6:00 pm
      </p>
  </div>
</li>

<li class="item event" >
  <div class="col-12 col-sm-2 event-type" >
    <h5 >
      Special Event
    </h5>
  </div>
    <div class="col-12 col-sm-7 item-content event-content" >
      <h3 class="title item-title event-title" >
        <a href="/events-and-training/event/3433/4378/">Conference sales (Wednesday)</a>
      </h3>
      <p ></p>
      <p >Stop by the conference sales table and browse our merchandise.</p>
      <p ></p>
    </div>
  <div class="col-12 col-sm-3 item-meta event-meta" >
    <h4 class="event-location" >
      Salon EF
    </h4>
      <p >
      3:00 pm - 6:00 pm
      </p>
  </div>
</li>
```

From it, I am looking to get a JSON representation like this:

```
{
    "BODY": [
        "Wednesday is a registration day.",
        "No talks scheduled.",
        ""
    ],
    "TITLE": "Conference registration (Wednesday)"
}
{
    "BODY": [
        "",
        "Stop by the conference sales table and browse our merchandise.",
        ""
    ],
    "TITLE": "Conference sales (Wednesday)"
}
```

My first thought was this:
```
<DIV >
  <h3><a @text:TITLE /></h3>
  <p @text:BODY />
</DIV>
```

But I get the first `p` tag, others ignored:

```
{
    "BODY": "Wednesday is a registration day.",
    "TITLE": "Conference registration (Wednesday)"
}
{
    "BODY": "",
    "TITLE": "Conference sales (Wednesday)"
}
```

I attempted with CSS `nth-child` selectors, but those selectors only seem to allow only a single reference (ranges like `n+2` will only grab the second child, ignoring the rest):

``
<DIV >
  <h3:nth-child(1)><a @text:TITLE /></h3>
  <p:nth-child(1n+2) @text:BODY /> # nth-child(n+2) throws an error!
</DIV>
```

The only way I can seem to get all of the `p` tags under `div` into `BODY` array is by omitting the `h3` tag:

```
<DIV ><p @text:BODY /></DIV>
```

Is this expected behavior? Is there a template I haven't thought of that can get both the `h3` text and an array of the sibling `p` tags under a `div`?

Thanks a lot!

**Comment by thomastrapp** [comment]
This will only match pairs of one `<h3>` and one `<p>`, repeatedly:
```
  <h3><a @text:TITLE /></h3>
  <p @text:BODY />
```

Making the `<h3>` optional (by adding a question mark) allows hext to match `<p>` without the heading:
```
<DIV class="item-content">
  <?h3> # <-- optional h3
    <a @text:TITLE />
  </h3>
  <p @text:BODY />
</DIV>
```
and will produce:
```
{
    "BODY": [
        "Wednesday is a registration day.",
        "No talks scheduled.",
        ""
    ],
    "TITLE": "Conference registration (Wednesday)"
}
{
    "BODY": [
        "",
        "Stop by the conference sales table and browse our merchandise.",
        ""
    ],
    "TITLE": "Conference sales (Wednesday)"
}
```

I hope this solves your problem.

I will think about this some more. The current rule matching might be too strict:

------

The hext template
```
<A/>
<B/>
```
means "Must match A __and__ B, then repeat".

-------

The hext template
```
<A/>
<?B/>
```
means "Must match A and optionally B, then repeat".

----

Maybe there should be a way to tell hext to repeat a rule for adjacent elements.

For example "Match `<h3>`, then match `<p>` and each adjacent `<p>`":
```
<h3 />
<p:repeat ... />
```

**Comment by brandonrobertz** [comment]
Thanks for the response and explanation. Unfortunately a `div` with a `p` is too general of a rule and will result in many unexpected records if the `h3` isn't a filtering criteria.

An adjacent siblings `repeat` rule would be useful in this case. That said, I kind of expected `p:nth-of-type(n)` or `p:nth-child(n+2)` to grab all the adjacent `p` siblings, but it appears those selectors boil down to only a single catch in the above case.

**Comment by thomastrapp** [comment]
Another solution came to mind:
```
<DIV >
  <h3><a @text:TITLE /></h3>
  <?p @text:BODY />
  <?p @text:BODY />
  <?p @text:BODY />
  <?p @text:BODY />
  <?p @text:BODY />
</DIV>
```
This will capture none or up to five paragraphs following the `<h3>`. But this is ugly \:)


> That said, I kind of expected p:nth-of-type(n) or p:nth-child(n+2) to grab all the adjacent p siblings, but it appears those selectors boil down to only a single catch in the above case.

Yes, `<p...>` can only consume a single paragraph at each turn. I agree that `nth-child(pattern)`, and the others, look like they might consume all elements that match `pattern`. This is unfortunate.

------

I really like the `:repeat` specifier.
`:repeat` should behave like optional rules (after the first match), continually searching for a match until another rule takes precedence or until there are no more elements left.
A rule with `:repeat` can also be made optional, that is, it may match none or many.

I will work on this in the next weeks.

> Is there anything I can do to help make this happen?

Thank you very much for your offer :+1: I will let you know.

------

### Example 1

Hext:
```
<h1 @text:h />       # h1-rule
<p:repeat @text:p /> # p-rule
```

HTML:

```
<h1>Heading 1</h1>    # h1-rule match
<p>one</p>            # p-rule match
<a>something else</a> # no match, skipped
<p>two</p>            # p-rule match
<h1>Heading 2</h1>    # h1-rule match -> new result
<p>three</p>          # p-rule match
```

Result:

```
{"h": "Heading 1", "p": ["one", "two"]}
{"h": "Heading 2", "p": "three"}
```


Hext:

```
<h1 @text:h />       # h1-rule
<*:repeat @text:p /> # star-rule
```

HTML:

```
<h1>Heading 1</h1>    # h1-rule match
<p>one</p>            # star-rule match
<a>something else</a> # star-rule match
<p>two</p>            # star-rule match
<h1>Heading 2</h1>    # star-rule matches, but h1-rule matches as well,
                      #   and h1-rule has precedence, therefore h1-rule takes over
<p>three</p>          # star-rule match
```


Result:

```
{"h": "Heading 1", "p": ["one", "something else", "two"]}
{"h": "Heading 2", "p": "three"}
```

### Example 2

Hext:

```
<h1 @text:heading />
<div:repeat>
  <a href:href @text:title />
</div>
```

HTML:

```
<h1>Heading 1</h1>
<div>
  <a href="one.html">One</a>
</div>

<h1>Heading 2</h1>
<div>
  <a href="two.html">Two</a>
</div>
<h2>Subheading 2.1</h2>
<div>
  <a href="three.html">Three</a>
</div>

<p>Archive</p>

<h1>Heading 3</h1>
<div>
  <a href="four.html">Four</a>
</div>
```

Result:

```
{heading: "Heading 1", href: "one.html", title: "One"}
{heading: "Heading 2", href: ["two.html", "three.html], title: ["Two", "Three"]}
{heading: "Heading 3", href: "four.html", title: "Four"}
```

### Example 3

Hext:

```
<h1 @text:heading />
<*:repeat @text:content /> # Match one or more elements that follow h1...
<?p @text="archive" /> # ..but stop if there is a paragraph containing "archive"
```

HTML:

```
<h1>Section 1</h1>
<p>Content 1</p>
<div>Content 2</div>
<p>Visit the archive for more content:</p>
<p>Ignored content 1</p>
<p>Ignored content 2</p>

<h1>Section 2</h1>
<p>Content 3</p>
<p>Content 4</p>
```

Result:

```
{heading: "Section 1", "content": ["Content 1", "Content 2"]}
{heading: "Section 2", "content": ["Content 3", "Content 4"]}
```

**Comment by thomastrapp** [comment]
Hext now has "greedy rules" (05c2fe7ff4056a38c85d2144dbf63cd213e4e829):

> Rules may be greedy. A rule marked with a plus sign does not stop at the first match,
> instead it continually searches for a match until a mandatory rule takes precedence or
> until there are no more elements left.
> A greedy rule can also be made optional, that is, it may match none or many.

```
# match <h1>, followed by at least one <p>
<h1/><+p />
# match <h1>, followed by zero or more <p>
<h1/><?+p />
```

As a next step, I'll setup automated (or semi-automated) releases via travis for pip and npm.

@brandonrobertz To achieve the result in your example:
```
<DIV >
  <h3><a @text:TITLE /></h3>
  <+p @text:BODY />
</DIV>
```

Test case: [hext-github-issue7.hext](https://github.com/thomastrapp/hext/blob/50f06377745b2a84b5fdd818897488f9b4ea944f/test/case/hext-github-issue7.hext), [hext-github-issue7.html](https://github.com/thomastrapp/hext/blob/50f06377745b2a84b5fdd818897488f9b4ea944f/test/case/hext-github-issue7.html), [hext-github-issue7.expected](https://github.com/thomastrapp/hext/blob/50f06377745b2a84b5fdd818897488f9b4ea944f/test/case/hext-github-issue7.expected).

**Comment by brandonrobertz** [comment]
Wow this incredible! This is going to help a lot of the scrapes I've been trying to do and facilitate the building of my Hext template building UI (https://github.com/brandonrobertz/hextractor/)

**Comment by thomastrapp** [comment]
My pleasure!

**Comment by thomastrapp** [comment]
I have updated the python and npm package (0.2.1 and 10.0.3, respectively).

Automated builds must wait for a later date.
Linux would be no problem, because I can use a docker image with all dependencies preinstalled. But I am not sure yet how to automate the Mac OS X builds (without building everything from source).
Maybe automating the build for Python on Linux only is good enough for now.

@brandonrobertz I love what you are doing with Hext — I was particularly surprised by [hext-emscripten](https://github.com/brandonrobertz/hext-emscripten). This would even make it possible to use Hext in a browser extension.
